inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'bin/webpack*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/models/dro_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/models/dro_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/models/dro_spec.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'